trigger:
  branches:
    include:
      - master
      - centralize
  paths:
    include:
      - codemodel/

pr:
  branches:
    include:
      - master
      - centralize
  paths:
    include:
      - codemodel/

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g npm
    npm install -g @microsoft/rush
    rush update
    rush rebuild -p @autorest/codemodel
    cd codemodel/ && rush test

  displayName: 'Build and Test'
